In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [2]:
df = pd.read_csv(r"C:\Users\TOLS\OneDrive - Cardiff Metropolitan University\Dissertation\DISSERTATION DATA\DISSERTATION.csv")
df.head(10)

year                   country  maize_yield  pot_yield  wheat_yield  \
0  1980  United States of America        57118     295245        22513   
1  1981  United States of America        68380     308199        23229   
2  1982  United States of America        71082     312544        23859   
3  1983  United States of America        50893     299754        26509   
4  1984  United States of America        66981     311082        26073   
5  1985  United States of America        74074     333689        25197   
6  1986  United States of America        74930     330540        23167   
7  1987  United States of America        75225     337394        25330   
8  1988  United States of America        53109     317265        22913   
9  1989  United States of America        72978     324007        22024   

   rice_yield  Production(Maize)Tonnes  Production Potatoes(Tonnes)  \
0       49461                168647008                     13785000   
1       54015                206222000                     15450000   
2       52791                209180000                     16108500   
3       51532                106030000                     15137600   
4       55523                194880000                     16422000   
5       60704                225453008                     18443008   
6       63340                208943008                     16408000   
7       62271                181142000                     17659200   
8       61801                125194000                     16167800   
9       64466                191319008                     16803008   

   Production Wheat(Tonnes)  Production Rice(Tonnes)  solar_rad      co2  \
0                  64799504                  6629250     894031  2713.57   
1                  75806304                  8289040     894031  2723.25   
2                  75251296                  6968900     851000  2734.78   
3                  65857904                  4523200     957440  2748.52   
4                  70618000                  6296300     800268  2761.06   
5                  65975008                  6122000     967417  2773.18   
6                  56897008                  6049000    1014520  2783.23   
7                  57361808                  5879000    1277547  2797.01   
8                  49320000                  7253000    1063344  2815.86   
9                  55428000                  7007400    1260174  2827.57   

     temp  precip  
0  4030.5   592.2  
1  4784.5   629.3  
2  4563.0   681.0  
3  4722.5   941.0  
4  4546.8   982.0  
5  4747.4   654.4  
6  4689.8   470.7  
7  4622.6   594.8  
8  4525.9   523.1  
9  4573.1  1060.1

### SUPPORT VECTOR REGRESSION APPLICATION FOR MAIZE YIELD

In [3]:
# Filtering the independent variables (X) and the dependent variable (y)
X = df[["solar_rad", "co2", "temp", "precip"]].values.astype(float)
y = df[["maize_yield"]].values.astype(float)
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
#Scaling or Standardizing the two variables for better analysis by calling the standardscaler() function from sklearn
scaledX = StandardScaler()
scaledy = StandardScaler()

In [6]:
#Transforming the variables into the standadized form.
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)
X

array([[-2.08000357e+00, -1.52066980e+00, -3.14024733e+00,
        -1.01693282e+00],
       [-2.08000357e+00, -1.46733358e+00,  4.20388438e-01,
        -8.22655421e-01],
       [-2.33787814e+00, -1.40380398e+00, -6.25607347e-01,
        -5.51923850e-01],
       [-1.70000849e+00, -1.32809742e+00,  1.27604065e-01,
         8.09588889e-01],
       [-2.64190297e+00, -1.25900278e+00, -7.02109070e-01,
         1.02428897e+00],
       [-1.64021869e+00, -1.19222231e+00,  2.45190047e-01,
        -6.91217076e-01],
       [-1.35794160e+00, -1.13684742e+00, -2.68160803e-02,
        -1.65317819e+00],
       [ 2.18316769e-01, -1.06092046e+00, -3.44156562e-01,
        -1.00331769e+00],
       [-1.06535096e+00, -9.57058099e-01, -8.00805738e-01,
        -1.37878101e+00],
       [ 1.14204505e-01, -8.92536709e-01, -5.77911828e-01,
         1.43326645e+00],
       [ 2.29235583e-01, -8.40963677e-01, -1.50541090e-01,
        -8.58675662e-02],
       [-5.58495082e-01, -7.77434076e-01,  8.59092766e-01,
      

In [7]:
y = y.ravel()
y

array([-1.72423835, -1.0470788 , -0.88461342, -2.09853405, -1.13119763,
       -0.70471098, -0.65324156, -0.63550385, -1.96529079, -0.77061107,
       -0.68631186, -1.05964552, -0.19651061, -1.35793965,  0.07226076,
       -0.87583476, -0.36204251, -0.37719472, -0.08491337, -0.10926514,
        0.00702207,  0.05644714, -0.27744266,  0.20754836,  0.8924644 ,
        0.42436929,  0.46796197,  0.52857081,  0.6262184 ,  1.04542958,
        0.59904062,  0.38191905, -0.51254245,  0.80942787,  1.29465941,
        1.19827451,  1.90237132,  1.5057682 ,  1.50029657,  1.16105539,
        1.31143507,  1.52212297])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state = 10)

In [10]:
gamma_values = [0.01]  # You can adjust these values according to your needs

In [11]:
from sklearn.svm import SVR

In [12]:
for gamma in gamma_values:
    svr_model = SVR(kernel='rbf', gamma=gamma)  # Using 'rbf' kernel with specified gamma
    svr_model.fit(X_train, y_train)

In [13]:
y_predict = svr_model.predict(X_test)
y_predict

array([ 0.68775279, -0.03473466,  0.35528105, -0.41946944,  0.7033092 ,
        0.12291534, -1.09192729, -0.25008342, -0.13220112,  0.05614562,
       -0.73677638])

In [14]:
y_predict= y_predict.reshape(-1,1)
y_predict

array([[ 0.68775279],
       [-0.03473466],
       [ 0.35528105],
       [-0.41946944],
       [ 0.7033092 ],
       [ 0.12291534],
       [-1.09192729],
       [-0.25008342],
       [-0.13220112],
       [ 0.05614562],
       [-0.73677638]])

In [15]:
y_pred=scaledy.inverse_transform(y_predict)
y_pred

array([[97232.39303736],
       [85216.53399672],
       [91702.97722656],
       [78817.91920124],
       [97491.11531128],
       [87838.44821554],
       [67634.11428254],
       [81635.01797617],
       [83595.54623516],
       [86727.98540364],
       [73540.71267699]])

In [16]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_predict)
r2

0.7451384534502385

In [17]:
intercept = svr_model.intercept_
intercept

array([-0.0865592])

In [18]:
from sklearn.metrics import mean_absolute_error as mae

In [19]:
error = mae(y_test, y_predict)
print("Mean absolute error : " + str(error))

Mean absolute error : 0.17143042806522787


In [20]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_predict)
print( "Mean Square Error :", mse)

Mean Square Error : 0.04924353448533301


In [21]:
# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_predict)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.222


### SUPPORT VECTOR REGRESSION FOR RICE YIELD

In [22]:
# Filtering the independent variables (X) and the dependent variable (y)
X = df[["solar_rad", "co2", "temp", "precip"]].values.astype(float)
y = df[["rice_yield"]].values.astype(float)
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
#Scaling or Standardizing the two variables for better analysis by calling the standardscaler() function from sklearn
scaledX = StandardScaler()
scaledy = StandardScaler()

In [25]:
#Transforming the variables into the standadized form.
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)
X

array([[-2.08000357e+00, -1.52066980e+00, -3.14024733e+00,
        -1.01693282e+00],
       [-2.08000357e+00, -1.46733358e+00,  4.20388438e-01,
        -8.22655421e-01],
       [-2.33787814e+00, -1.40380398e+00, -6.25607347e-01,
        -5.51923850e-01],
       [-1.70000849e+00, -1.32809742e+00,  1.27604065e-01,
         8.09588889e-01],
       [-2.64190297e+00, -1.25900278e+00, -7.02109070e-01,
         1.02428897e+00],
       [-1.64021869e+00, -1.19222231e+00,  2.45190047e-01,
        -6.91217076e-01],
       [-1.35794160e+00, -1.13684742e+00, -2.68160803e-02,
        -1.65317819e+00],
       [ 2.18316769e-01, -1.06092046e+00, -3.44156562e-01,
        -1.00331769e+00],
       [-1.06535096e+00, -9.57058099e-01, -8.00805738e-01,
        -1.37878101e+00],
       [ 1.14204505e-01, -8.92536709e-01, -5.77911828e-01,
         1.43326645e+00],
       [ 2.29235583e-01, -8.40963677e-01, -1.50541090e-01,
        -8.58675662e-02],
       [-5.58495082e-01, -7.77434076e-01,  8.59092766e-01,
      

In [26]:
y=y.ravel()
y

array([-2.01135204, -1.58549599, -1.69995532, -1.8176876 , -1.4444791 ,
       -0.9599907 , -0.71349168, -0.81345657, -0.85740745, -0.60819657,
       -0.84113628, -0.63017201, -0.62428072, -0.86096093, -0.38516919,
       -0.74463135, -0.22227037, -0.45549061, -0.70105451, -0.48784595,
       -0.05357377,  0.17179142,  0.25810348,  0.35432787,  0.68807408,
        0.30626243,  0.59315887,  0.93017801,  0.53873457,  0.78953517,
        0.41193159,  0.77045862,  1.18584126,  1.42719709,  1.30441515,
        1.19248065,  0.94925457,  1.23222348,  1.42542036,  1.19594061,
        1.34948818,  1.44328125])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state = 10)

In [29]:
gamma_values = [0.01]  # You can adjust these values according to your needs

In [30]:
from sklearn.svm import SVR

In [31]:
for gamma in gamma_values:
    svr_model = SVR(kernel='rbf', gamma=gamma)  # Using 'rbf' kernel with specified gamma
    svr_model.fit(X_train, y_train)

In [32]:
y_predict = svr_model.predict(X_test)
y_predict

array([ 0.83656401, -0.02301362,  0.34609402, -0.42381786,  0.71901725,
        0.0560499 , -1.24487732, -0.30851873, -0.13828825,  0.04604132,
       -0.83272057])

In [33]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
r2 = r2_score(y_test, y_predict)
r2

0.7972938493642707

In [34]:
error=mean_absolute_error(y_test, y_predict)
print('Mean absolute error:', error)

Mean absolute error: 0.27988467524389227


In [35]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_predict)
print( "Mean Square Error :", mse)

Mean Square Error : 0.10195544829218291


In [36]:
# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_predict)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.319


## SUPPORT VECTOR REGRESSION FOR WHEAT YIELD

In [37]:
# Filtering the independent variables (X) and the dependent variable (y)
X = df[["solar_rad", "co2", "temp", "precip"]].values.astype(float)
y = df[["wheat_yield"]].values.astype(float)
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
#Scaling or Standardizing the two variables for better analysis by calling the standardscaler() function from sklearn
scaledX = StandardScaler()
scaledy = StandardScaler()

In [40]:
#Transforming the variables into the standadized form.
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)
X

array([[-2.08000357e+00, -1.52066980e+00, -3.14024733e+00,
        -1.01693282e+00],
       [-2.08000357e+00, -1.46733358e+00,  4.20388438e-01,
        -8.22655421e-01],
       [-2.33787814e+00, -1.40380398e+00, -6.25607347e-01,
        -5.51923850e-01],
       [-1.70000849e+00, -1.32809742e+00,  1.27604065e-01,
         8.09588889e-01],
       [-2.64190297e+00, -1.25900278e+00, -7.02109070e-01,
         1.02428897e+00],
       [-1.64021869e+00, -1.19222231e+00,  2.45190047e-01,
        -6.91217076e-01],
       [-1.35794160e+00, -1.13684742e+00, -2.68160803e-02,
        -1.65317819e+00],
       [ 2.18316769e-01, -1.06092046e+00, -3.44156562e-01,
        -1.00331769e+00],
       [-1.06535096e+00, -9.57058099e-01, -8.00805738e-01,
        -1.37878101e+00],
       [ 1.14204505e-01, -8.92536709e-01, -5.77911828e-01,
         1.43326645e+00],
       [ 2.29235583e-01, -8.40963677e-01, -1.50541090e-01,
        -8.58675662e-02],
       [-5.58495082e-01, -7.77434076e-01,  8.59092766e-01,
      

In [41]:
y=y.ravel()
y

array([-1.49968789, -1.28754397, -1.10088103, -0.31571151, -0.44489412,
       -0.7044445 , -1.30591398, -0.66503788, -1.38117173, -1.64457389,
       -0.29852667, -1.34413544, -0.33822958, -0.55570672, -0.6828153 ,
       -1.03984521, -0.94384713, -0.29645264,  0.43242171,  0.34116427,
        0.19657456, -0.16489971, -1.18739782,  0.63330659,  0.43005138,
        0.19450053, -0.47067138, -0.15660358,  0.77048903,  0.68812031,
        1.0644091 ,  0.54738238,  1.06055732,  1.21433203,  0.5343456 ,
        0.51093866,  2.32097661,  1.06677942,  1.31270044,  2.12483238,
        1.73106246,  0.65404691])

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state = 10)

In [44]:
gamma_values = [0.01]  # You can adjust these values according to your needs

In [45]:
from sklearn.svm import SVR

In [46]:
for gamma in gamma_values:
    svr_model = SVR(kernel='rbf', gamma=gamma)  # Using 'rbf' kernel with specified gamma
    svr_model.fit(X_train, y_train)

In [47]:
y_predict = svr_model.predict(X_test)
y_predict

array([ 0.26389742, -0.21947967,  0.28924868, -0.49861249,  0.60757566,
        0.24141877, -0.84158203, -0.20609117, -0.25014936, -0.00519012,
       -0.68004248])

In [48]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
r2 = r2_score(y_test, y_predict)
r2

0.49424447979521

In [49]:
mae = mean_absolute_error(y_test, y_predict)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 0.3463024826064814


In [50]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_predict)
print( "Mean Square Error :", mse)

Mean Square Error : 0.19136569110960222


In [51]:
# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_predict)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.437


### SUPPORT VECTOR REGRESSION FOR POTATO YIELD

In [52]:
# Filtering the independent variables (X) and the dependent variable (y)
X = df[["solar_rad", "co2", "temp", "precip"]].values.astype(float)
y = df[["pot_yield"]].values.astype(float)
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
#Scaling or Standardizing the two variables for better analysis by calling the standardscaler() function from sklearn
scaledX = StandardScaler()
scaledy = StandardScaler()

In [55]:
#Transforming the variables into the standadized form.
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)
X

array([[-2.08000357e+00, -1.52066980e+00, -3.14024733e+00,
        -1.01693282e+00],
       [-2.08000357e+00, -1.46733358e+00,  4.20388438e-01,
        -8.22655421e-01],
       [-2.33787814e+00, -1.40380398e+00, -6.25607347e-01,
        -5.51923850e-01],
       [-1.70000849e+00, -1.32809742e+00,  1.27604065e-01,
         8.09588889e-01],
       [-2.64190297e+00, -1.25900278e+00, -7.02109070e-01,
         1.02428897e+00],
       [-1.64021869e+00, -1.19222231e+00,  2.45190047e-01,
        -6.91217076e-01],
       [-1.35794160e+00, -1.13684742e+00, -2.68160803e-02,
        -1.65317819e+00],
       [ 2.18316769e-01, -1.06092046e+00, -3.44156562e-01,
        -1.00331769e+00],
       [-1.06535096e+00, -9.57058099e-01, -8.00805738e-01,
        -1.37878101e+00],
       [ 1.14204505e-01, -8.92536709e-01, -5.77911828e-01,
         1.43326645e+00],
       [ 2.29235583e-01, -8.40963677e-01, -1.50541090e-01,
        -8.58675662e-02],
       [-5.58495082e-01, -7.77434076e-01,  8.59092766e-01,
      

In [56]:
y=y.ravel()
y

array([-1.66360986, -1.46382342, -1.39681152, -1.59406863, -1.4193596 ,
       -1.07069725, -1.11926352, -1.01355592, -1.32400067, -1.22002042,
       -1.14596032, -0.96443443, -0.62584314, -0.58639172, -0.35848959,
       -0.62578145, -0.16448668, -0.25193373, -0.2883006 , -0.01150832,
        0.37089903, -0.02019133,  0.03943306,  0.12142046,  0.54041059,
        0.52731667,  0.58354806,  0.63578495,  0.63635559,  0.94593666,
        0.71447187,  0.67568363,  0.84285093,  0.93253428,  1.05483677,
        1.01617191,  1.28465133,  1.24577055,  1.45223505,  1.6102875 ,
        1.74667097,  1.35126223])

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state = 10)

In [59]:
gamma_values = [0.01]  # You can adjust these values according to your needs

In [60]:
from sklearn.svm import SVR

In [61]:
for gamma in gamma_values:
    svr_model = SVR(kernel='rbf', gamma=gamma)  # Using 'rbf' kernel with specified gamma
    svr_model.fit(X_train, y_train)

In [62]:
y_predict = svr_model.predict(X_test)
y_predict

array([ 0.67215976, -0.08293774,  0.37974718, -0.54364926,  0.75750687,
        0.17564446, -1.37421696, -0.29068925, -0.25959192,  0.04378024,
       -0.87086827])

In [63]:
from sklearn.metrics import r2_score
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
r2 = r2_score(y_test, y_predict)
r2

0.9079164761439187

In [64]:
mae = mean_absolute_error(y_test, y_predict)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 0.1433650891707966


In [65]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_predict)
print( "Mean Square Error :", mse)

Mean Square Error : 0.04069004436447771


In [66]:
# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_predict)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.202
