In [1]:
import numpy as np # for array operations
import pandas as pd # for working with DataFrames
import requests, io # for HTTP requests and I/O commands
import matplotlib.pyplot as plt # for data visualization
%matplotlib inline

from sklearn.model_selection import train_test_split # for splitting the data
from sklearn.metrics import mean_squared_error # for calculating the cost function
from sklearn.tree import DecisionTreeRegressor # for building the model

In [2]:
df=pd.read_csv(r"C:\Users\TOLS\OneDrive - Cardiff Metropolitan University\Dissertation\DISSERTATION DATA\DISSERTATION.csv")
df.head(5)

year                   country  maize_yield  pot_yield  wheat_yield  \
0  1980  United States of America        57118     295245        22513   
1  1981  United States of America        68380     308199        23229   
2  1982  United States of America        71082     312544        23859   
3  1983  United States of America        50893     299754        26509   
4  1984  United States of America        66981     311082        26073   

   rice_yield  Production(Maize)Tonnes  Production Potatoes(Tonnes)  \
0       49461                168647008                     13785000   
1       54015                206222000                     15450000   
2       52791                209180000                     16108500   
3       51532                106030000                     15137600   
4       55523                194880000                     16422000   

   Production Wheat(Tonnes)  Production Rice(Tonnes)  solar_rad      co2  \
0                  64799504                  6629250     894031  2713.57   
1                  75806304                  8289040     894031  2723.25   
2                  75251296                  6968900     851000  2734.78   
3                  65857904                  4523200     957440  2748.52   
4                  70618000                  6296300     800268  2761.06   

     temp  precip  
0  4030.5   592.2  
1  4784.5   629.3  
2  4563.0   681.0  
3  4722.5   941.0  
4  4546.8   982.0

In [3]:
df.columns

Index(['year', 'country', 'maize_yield', 'pot_yield', 'wheat_yield',
       'rice_yield', 'Production(Maize)Tonnes', 'Production Potatoes(Tonnes)',
       'Production Wheat(Tonnes)', 'Production Rice(Tonnes)', 'solar_rad',
       'co2', 'temp', 'precip'],
      dtype='object')

## DECISION TREE REGRESSION FOR MAIZE YIELD

In [4]:
dfm=df[['maize_yield', 'solar_rad', 'co2', 'temp', 'precip']]
dfm.head()

maize_yield  solar_rad      co2    temp  precip
0        57118     894031  2713.57  4030.5   592.2
1        68380     894031  2723.25  4784.5   629.3
2        71082     851000  2734.78  4563.0   681.0
3        50893     957440  2748.52  4722.5   941.0
4        66981     800268  2761.06  4546.8   982.0

In [5]:
#Separating the features and the target variable
X = dfm.drop('maize_yield', axis = 1).values.astype(float) # Features
y = dfm[["maize_yield"]].values.astype(float) # Target
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [6]:
### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
scaledX = StandardScaler()
scaledy = StandardScaler()

In [7]:
# Storing the fit object for later reference
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)

In [8]:
# Splitting the dataset into training and testing set (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [9]:
# Initializing the Decision Tree Regression model
model = DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state = 0)

# Fitting the Decision Tree Regression model to the data
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state=0)

In [10]:
# Predicting the target values of the test set
y_pred = model.predict(X_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.669


In [11]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print( "Mean Square Error :", mse)

Mean Square Error : 0.4473310903594326


In [12]:
from sklearn.metrics import mean_absolute_error as mae
error = mae(y_test, y_pred)
print("Mean absolute error : " + str(error))

Mean absolute error : 0.4935645906545388


In [13]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.6903033052723788

## DECISION TREE RRGRESSION ANALYSIS FOR RICE YIELD

In [14]:
df.head(20)

year                   country  maize_yield  pot_yield  wheat_yield  \
0   1980  United States of America        57118     295245        22513   
1   1981  United States of America        68380     308199        23229   
2   1982  United States of America        71082     312544        23859   
3   1983  United States of America        50893     299754        26509   
4   1984  United States of America        66981     311082        26073   
5   1985  United States of America        74074     333689        25197   
6   1986  United States of America        74930     330540        23167   
7   1987  United States of America        75225     337394        25330   
8   1988  United States of America        53109     317265        22913   
9   1989  United States of America        72978     324007        22024   
10  1990  United States of America        74380     328809        26567   
11  1991  United States of America        68171     340579        23038   
12  1992  United States of America        82526     362533        26433   
13  1993  United States of America        63210     365091        25699   
14  1994  United States of America        86996     379868        25270   
15  1995  United States of America        71228     362537        24065   
16  1996  United States of America        79773     392447        24389   
17  1997  United States of America        79521     386777        26574   
18  1998  United States of America        84382     384419        29034   
19  1999  United States of America        83977     402366        28726   

    rice_yield  Production(Maize)Tonnes  Production Potatoes(Tonnes)  \
0        49461                168647008                     13785000   
1        54015                206222000                     15450000   
2        52791                209180000                     16108500   
3        51532                106030000                     15137600   
4        55523                194880000                     16422000   
5        60704                225453008                     18443008   
6        63340                208943008                     16408000   
7        62271                181142000                     17659200   
8        61801                125194000                     16167800   
9        64466                191319008                     16803008   
10       61975                201532000                     18239008   
11       64231                189867780                     18943008   
12       64294                240719220                     19294000   
13       61763                160985760                     19520300   
14       66851                255294970                     21292760   
15       63007                187969950                     20189350   
16       68593                234517750                     22645780   
17       66099                233864300                     21186890   
18       63473                247882020                     21575890   
19       65753                239548580                     21685930   

    Production Wheat(Tonnes)  Production Rice(Tonnes)  solar_rad      co2  \
0                   64799504                  6629250     894031  2713.57   
1                   75806304                  8289040     894031  2723.25   
2                   75251296                  6968900     851000  2734.78   
3                   65857904                  4523200     957440  2748.52   
4                   70618000                  6296300     800268  2761.06   
5                   65975008                  6122000     967417  2773.18   
6                   56897008                  6049000    1014520  2783.23   
7                   57361808                  5879000    1277547  2797.01   
8                   49320000                  7253000    1063344  2815.86   
9                   55428000                  7007400    1260174  2827.57   
10                  74294000                  7080000    1279369  28

In [15]:
dfr=df[['rice_yield', 'solar_rad', 'co2', 'temp', 'precip']]
dfr.head()

rice_yield  solar_rad      co2    temp  precip
0       49461     894031  2713.57  4030.5   592.2
1       54015     894031  2723.25  4784.5   629.3
2       52791     851000  2734.78  4563.0   681.0
3       51532     957440  2748.52  4722.5   941.0
4       55523     800268  2761.06  4546.8   982.0

In [16]:
#Separating the features and the target variable
X = dfr.drop('rice_yield', axis = 1).values.astype(float) # Features
y = dfr[["rice_yield"]].values.astype(float) # Target
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [17]:
### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
scaledX = StandardScaler()
scaledy = StandardScaler()

In [18]:
# Storing the fit object for later reference
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)

In [19]:
# Splitting the dataset into training and testing set (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [20]:
# Initializing the Decision Tree Regression model
model = DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state = 0)

# Fitting the Decision Tree Regression model to the data
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state=0)

In [21]:
# Predicting the target values of the test set
y_pred = model.predict(X_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.306


In [22]:
from sklearn.metrics import mean_absolute_error as mae
error = mae(y_test, y_pred)
print("Mean absolute error : " + str(error))

Mean absolute error : 0.2506665412458626


In [23]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.9298281263821985

In [24]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print( "Mean Square Error :", mse)

Mean Square Error : 0.09372041681876316


## DECISION TREE RRGRESSION ANALYSIS FOR WHEAT YIELD

In [25]:
dfw=df[['wheat_yield', 'solar_rad', 'co2', 'temp', 'precip']]
dfw.head()

wheat_yield  solar_rad      co2    temp  precip
0        22513     894031  2713.57  4030.5   592.2
1        23229     894031  2723.25  4784.5   629.3
2        23859     851000  2734.78  4563.0   681.0
3        26509     957440  2748.52  4722.5   941.0
4        26073     800268  2761.06  4546.8   982.0

In [26]:
#Separating the features and the target variable
X = dfw.drop('wheat_yield', axis = 1).values.astype(float) # Features
y = dfw[["wheat_yield"]].values.astype(float) # Target
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [27]:
### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
scaledX = StandardScaler()
scaledy = StandardScaler()

In [28]:
# Storing the fit object for later reference
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)

In [29]:
# Splitting the dataset into training and testing set (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [30]:
# Initializing the Decision Tree Regression model
model = DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state = 0)

# Fitting the Decision Tree Regression model to the data
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state=0)

In [31]:
# Predicting the target values of the test set
y_pred = model.predict(X_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.862


In [32]:
from sklearn.metrics import mean_absolute_error as mae
error = mae(y_test, y_pred)
print("Mean absolute error : " + str(error))

Mean absolute error : 0.6701035735525548


In [33]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.28191237999880536

In [34]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print( "Mean Square Error :", mse)

Mean Square Error : 0.7433924998733519


## DECISION TREE RRGRESSION ANALYSIS FOR POTATO YIELD

In [35]:
dfp=df[['pot_yield', 'solar_rad', 'co2', 'temp', 'precip']]
dfp.head()

pot_yield  solar_rad      co2    temp  precip
0     295245     894031  2713.57  4030.5   592.2
1     308199     894031  2723.25  4784.5   629.3
2     312544     851000  2734.78  4563.0   681.0
3     299754     957440  2748.52  4722.5   941.0
4     311082     800268  2761.06  4546.8   982.0

In [36]:
#Separating the features and the target variable
X = dfp.drop('pot_yield', axis = 1).values.astype(float) # Features
y = dfp[["pot_yield"]].values.astype(float) # Target
X

array([[8.940310e+05, 2.713570e+03, 4.030500e+03, 5.922000e+02],
       [8.940310e+05, 2.723250e+03, 4.784500e+03, 6.293000e+02],
       [8.510000e+05, 2.734780e+03, 4.563000e+03, 6.810000e+02],
       [9.574400e+05, 2.748520e+03, 4.722500e+03, 9.410000e+02],
       [8.002680e+05, 2.761060e+03, 4.546800e+03, 9.820000e+02],
       [9.674170e+05, 2.773180e+03, 4.747400e+03, 6.544000e+02],
       [1.014520e+06, 2.783230e+03, 4.689800e+03, 4.707000e+02],
       [1.277547e+06, 2.797010e+03, 4.622600e+03, 5.948000e+02],
       [1.063344e+06, 2.815860e+03, 4.525900e+03, 5.231000e+02],
       [1.260174e+06, 2.827570e+03, 4.573100e+03, 1.060100e+03],
       [1.279369e+06, 2.836930e+03, 4.663600e+03, 7.700000e+02],
       [1.147922e+06, 2.848460e+03, 4.877400e+03, 5.254000e+02],
       [1.106325e+06, 2.854980e+03, 4.273000e+03, 6.694000e+02],
       [1.252046e+06, 2.859600e+03, 4.590500e+03, 9.044000e+02],
       [1.273503e+06, 2.873380e+03, 4.634500e+03, 8.351000e+02],
       [1.217411e+06, 2.8

In [37]:
### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
scaledX = StandardScaler()
scaledy = StandardScaler()

In [38]:
# Storing the fit object for later reference
X = scaledX.fit_transform(X)
y = scaledy.fit_transform(y)

In [39]:
# Splitting the dataset into training and testing set (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [40]:
# Initializing the Decision Tree Regression model
model = DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state = 0)

# Fitting the Decision Tree Regression model to the data
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, min_samples_split=5, random_state=0)

In [41]:
# Predicting the target values of the test set
y_pred = model.predict(X_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)), '.3f'))
print("\nRMSE: ", rmse)


RMSE:  0.237


In [42]:
from sklearn.metrics import mean_absolute_error as mae
error = mae(y_test, y_pred)
print("Mean absolute error : " + str(error))

Mean absolute error : 0.19218788402125228


In [43]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.9556231167695265

In [44]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print( "Mean Square Error :", mse)

Mean Square Error : 0.05600584805038207
